short_positions:
  pct_short_ge: 5.0
  pct_short_change_ge: 0.50
  abs_shares_cover_ge: 200000
  adv_window_days: 30
  dtc_ge: 3.0
  top_n: 25

gross_shorts:
  absolute_qty_ge: 200000
  as_percent_issued_ge: 0.10
  top_n: 25
